// Listado de usuarios para usar en el componente data Table
// Campos para la tabla de usuario
/*
 * id: ID del usuario
 * C.I: Cedula del usuario
 * firstName: Nombre del usuario
 * lastName: Apellido del usuario
 * email: Email del usuario
 * username: Nombre de usuario
 * password: Contraseña del usuario
 * phone: Teléfono del usuario
 * address: Dirección del usuario
 * fullName: Nombre completo del usuario
 * role: Rol del usuario
 * status: Estado del usuario
 */
export const users = [
  {
    id: 1,
    CI: "1234567890",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@gmail.com",
    username: "john.doe",
    password: "123456",
    phone: "1234567890",
    address: "123 Main St",
    fullName: "",
    role: "administrador",
    status: true,
  },
  {
    id: 2,
    CI: "1234567888",
    firstName: "Jane",
    lastName: "Doe",
    email: "jane.doe@gmail.com",
    username: "jane.doe",
    password: "654321",
    phone: "0987654321",
    address: "456 Elm St",
    fullName: "",
    role: "asistente",
    status: false,
  },
  {
    id: 3,
    CI: "1234567777",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@gmail.com",
    username: "alice.smith",
    password: "password1",
    phone: "1112223333",
    address: "789 Maple Ave",
    fullName: "",
    role: "medico",
    status: true,
  },
  {
    id: 4,
    CI: "1234566666",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@gmail.com",
    username: "bob.johnson",
    password: "password2",
    phone: "4445556666",
    address: "101 Pine St",
    fullName: "",
    role: "contable",
    status: false,
  },
  {
    id: 5,
    CI: "1234565555",
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie.brown@gmail.com",
    username: "charlie.brown",
    password: "abc123",
    phone: "7778889999",
    address: "102 Oak St",
    fullName: "",
    role: "emisor",
    status: true,
  },
  {
    id: 6,
    CI: "1234564444",
    firstName: "Diana",
    lastName: "Prince",
    email: "diana.prince@gmail.com",
    username: "diana.prince",
    password: "wonderwoman",
    phone: "1231231234",
    address: "103 Birch St",
    fullName: "",
    role: "contable",
    status: false,
  },
  {
    id: 7,
    CI: "1234563333",
    firstName: "Elliot",
    lastName: "Anderson",
    email: "elliot.anderson@gmail.com",
    username: "elliot.anderson",
    password: "mrrobot",
    phone: "5556667777",
    address: "104 Cedar St",
    fullName: "",
    role: "emisor",
    status: true,
  },
  {
    id: 8,
    CI: "1234562222",
    firstName: "Fiona",
    lastName: "Gallagher",
    email: "fiona.gallagher@gmail.com",
    username: "fiona.gallagher",
    password: "shameless",
    phone: "8889990000",
    address: "105 Spruce St",
    fullName: "",
    role: "contable",
    status: true,
  },
  {
    id: 9,
    CI: "1234561111",
    firstName: "Gregory",
    lastName: "House",
    email: "gregory.house@gmail.com",
    username: "gregory.house",
    password: "diagnostic",
    phone: "2223334444",
    address: "106 Redwood St",
    fullName: "",
    role: "medico",
    status: false,
  },
  {
    id: 10,
    CI: "1234560000",
    firstName: "Hannah",
    lastName: "Baker",
    email: "hannah.baker@gmail.com",
    username: "hannah.baker",
    password: "13reasons",
    phone: "3334445555",
    address: "107 Cypress St",
    fullName: "",
    role: "administrador",
    status: true,
  },
  {
    id: 11,
    CI: "9876543210",
    firstName: "Isaac",
    lastName: "Newton",
    email: "isaac.newton@gmail.com",
    username: "isaac.newton",
    password: "gravity123",
    phone: "1112220000",
    address: "108 Apple St",
    fullName: "",
    role: "contable",
    status: true,
  },
  {
    id: 12,
    CI: "9876543209",
    firstName: "Marie",
    lastName: "Curie",
    email: "marie.curie@gmail.com",
    username: "marie.curie",
    password: "radioactive",
    phone: "3335559999",
    address: "109 Radiation Rd",
    fullName: "",
    role: "contable",
    status: true,
  },
  {
    id: 13,
    CI: "9876543208",
    firstName: "Albert",
    lastName: "Einstein",
    email: "albert.einstein@gmail.com",
    username: "albert.einstein",
    password: "emc2rulez",
    phone: "4447778888",
    address: "110 Theory Ln",
    fullName: "",
    role: "contable",
    status: true,
  },
  {
    id: 14,
    CI: "9876543207",
    firstName: "Ada",
    lastName: "Lovelace",
    email: "ada.lovelace@gmail.com",
    username: "ada.lovelace",
    password: "firstcoder",
    phone: "9998887777",
    address: "111 Algorithm Ave",
    fullName: "",
    role: "contable",
    status: false,
  },
  {
    id: 15,
    CI: "9876543206",
    firstName: "Nikola",
    lastName: "Tesla",
    email: "nikola.tesla@gmail.com",
    username: "nikola.tesla",
    password: "alternating",
    phone: "6665554444",
    address: "112 Current Ct",
    fullName: "",
    role: "contable",
    status: true,
  },
  {
    id: 16,
    CI: "9876543205",
    firstName: "Katherine",
    lastName: "Johnson",
    email: "katherine.johnson@gmail.com",
    username: "katherine.johnson",
    password: "nasa123",
    phone: "2221113333",
    address: "113 Orbit Way",
    fullName: "",
    role: "emisor",
    status: false,
  },
  {
    id: 17,
    CI: "9876543204",
    firstName: "Leonardo",
    lastName: "Da Vinci",
    email: "leonardo.davinci@gmail.com",
    username: "leonardo.davinci",
    password: "monalisa",
    phone: "5556667777",
    address: "114 Canvas Dr",
    fullName: " Vinci",
    role: "emisor",
    status: true,
  },
  {
    id: 18,
    CI: "9876543203",
    firstName: "Galileo",
    lastName: "Galilei",
    email: "galileo.galilei@gmail.com",
    username: "galileo.galilei",
    password: "stars123",
    phone: "1239876543",
    address: "115 Telescope St",
    fullName: "",
    role: "medico",
    status: false,
  },
  {
    id: 19,
    CI: "9876543202",
    firstName: "Rosalind",
    lastName: "Franklin",
    email: "rosalind.franklin@gmail.com",
    username: "rosalind.franklin",
    password: "dnahelix",
    phone: "8881112222",
    address: "116 Double Helix Ln",
    fullName: "",
    role: "medico",
    status: true,
  },
  {
    id: 20,
    CI: "9876543201",
    firstName: "Alan",
    lastName: "Turing",
    email: "alan.turing@gmail.com",
    username: "alan.turing",
    password: "enigma123",
    phone: "4443332222",
    address: "117 Machine Way",
    fullName: "",
    role: "medico",
    status: true,
  },
];

export const roles = [
  {
    id: 1,
    name: "Administrador",
  },
  {
    id: 2,
    name: "Asistente",
  },
  {
    id: 3,
    name: "Medico",
  },
  {
    id: 4,
    name: "Emisor",
  },
  {
    id: 5,
    name: "Contable",
  },
];
